IMG_SEA = 'img/sea.bmp'
IMG_SEASTAR = 'img/seastar2.png'
IMG_MAP = 'img/map.jpg'
IMG_MAN = 'img/man.png'
IMG_MONEY = 'img/money.png'
ARRAY_CONFOCAL = 'img/confocal.npy'
IMG_ONE = 'img/1.jpg'
IMG_TWO = 'img/2.jpg'
